apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-management.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_USERNAME: {{ .Values.secrets.mongoUsername | quote }}
  MONGO_PASSWORD: {{ .Values.secrets.mongoPassword | quote }}
  MONGODB_CONNECTION_STRING: {{ .Values.secrets.mongoConnectionString | quote }}
